name: Mirror Repository to Organization

on:
  push:
    branches:
      - main  # Change this to the branch you want to mirror

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Set up Git configuration
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Push to organization repository
        run: |
          git remote add target https://$GITHUB_ACTOR:${{ secrets.GITHUBACTIONWORKFLOW }}@github.com/karolinskaimaging/ctprotocols.git
          git push target --mirror
