name: Mirror Repository to Organization

on:
  push:
    branches:
      - main  # Change this to the branch you want to mirror

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Push to organization repository
        run: |
          git remote add target https://$GITHUB_ACTOR:${{ secrets.GithubActionWorkflow }}@github.com/karolinskaimaging/ctprotocols.git
          git push target --mirror
